/******************************************************************************
*  @file       	soundsAndMusic.h
*  @brief      	Sounds and music handler
*  @author     	Ron
*  @created 	November 17, 2017
*  @modified   	November 18, 2017
*      
*  @par [explanation]
*		> Holds code for managing sounds and music
******************************************************************************/

// Music data is included as .s file generated by the text2data tool from music.ftm
extern const unsigned char music_music_data[];

// Sound effects enum
enum
{
	SFX_START = 0,
	SFX_ITEM,
	SFX_RESPAWN1,
	SFX_RESPAWN2
};

// Music enum
enum
{
	MUSIC_LEVEL = 0,
	MUSIC_GAME,
	MUSIC_CLEAR,
	MUSIC_GAME_OVER,
	MUSIC_WELL_DONE,
	MUSIC_LOSE
};

